#!/usr/bin/env bash

# Format all staged terraform files
for file in `git diff --cached --name-only --diff-filter=ACMR | grep "\.tf$"`
do
  echo "Formatting ${file}"
  terraform fmt ${file}
  git add ${file}
done

# If no files left in index after formatting - fail
ret=0
if [[ ! "`git diff --cached --name-only`" ]]; then
  1>&2 echo "No files left after formatting"
  exit 1
fi