controller:
  replicas: 1
  apisvc:
    type: ClusterIP
  ranchersso:
    enabled: true
  secret:
    enabled: true
    data:
      sysinitcfg.yaml:
        Cluster_Name: cluster-two
  federation:
    managedsvc:
      type: ClusterIP
      ingress:
        enabled: true
        host:  neuvector-managed.cluster-two.plgrnd.be
        path: "/"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-http-prod
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        tls: true
        secretName: neuvector-managed-tls-secret

cve:
  scanner:
    replicas: 1

k3s:
  enabled: true

global:
  cattle:
    url: https://rancher.plgrnd.be/
