apiVersion: ui.cattle.io/v1
kind: NavLink
metadata:
  name: opni
spec:
  sideLabel: Opni
  target: _blank
  toService:
    name: opni-admin-dashboard
    namespace: opni
    port: '12080'
    scheme: http
