replicaCount: 1

disableUsage: false

gateway:
  enabled: true
  # Service type for the external gateway APIs
  serviceType: ClusterIP
  # Gateway hostname (required if gateway.enabled is true)
  hostname: "opni.plgrnd.be"
  # Auth provider config (required if gateway.enabled is true)
  auth:
    # Noauth provider:
    provider: noauth
    noauth:
      grafanaHostname: grafana.plgrnd.be
    # Openid provider:
    # provider: openid
    # openid:
    #   {} # see docs

  # Alerting
  alerting:
    enabled: false
  s3:
    internal: {}

opni-prometheus-crd:
  enabled: false # set to false if `opni-agent.kube-prometheus-stack.enabled` is true

opni-agent:
  enabled: true
  address: opni
  fullnameOverride: opni-agent
  bootstrapInCluster:
    enabled: true
    managementAddress: opni-internal:11090
  agent:
    version: v2
  kube-prometheus-stack:
    enabled: true
  disableUsage: false

kube-prometheus-stack:
  grafana:
    enabled: false # disable the default Grafana deployment
  prometheus:
    enabled: false # disable the default Prometheus deployment
  alertmanager:
    enabled: false # disable the default Alertmanager deployment
